name: wise_util
description: Wiseasy flutter project util package.
version: 0.0.3+3
homepage: https://github.com/cctangwen/wise_util.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  intl: ^0.17.0

  # Getx
  get: ^4.3.8

  # 简单数据存储
  shared_preferences: ^2.0.7

  # 网络请求
  dio: ^4.0.1

  # 时区转换
  timezone: ^0.8.0

  # 包检查
  package_info: ^2.0.2

  # 瀑布流
  flutter_staggered_grid_view: ^0.6.1

  # 下拉刷新
  pull_to_refresh: ^2.0.0

  # 权限控制
  permission_handler: ^8.1.6

  # 路径
  path_provider: ^2.0.2

  # 应用安装插件
  app_installer: ^1.1.0

  # 微光
  shimmer: ^2.0.0

  # 分组列表
  grouped_list: ^4.2.0

  # 网络图片缓存
  cached_network_image: ^3.1.0

  flutter_styled_toast: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Regular                # 字体别名
      fonts:
        - asset: assets/fonts/AlibabaSans-Regular.otf # 字体文件目录
          weight: 700              # 权重 700表示粗体，相当于bold