name: wise_util
description: Wiseasy flutter project util package.
version: 0.0.3+3
homepage: https://github.com/cctangwen/wise_util.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.17.0

  get: ^4.3.8

  #  Wraps platform-specific persistent storage for simple data
  #  (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.).
  #  Data may be persisted to disk asynchronously,
  #  and there is no guarantee that writes will be persisted to disk after returning,
  #  so this plugin must not be used for storing critical data.
  #  Supported data types are int, double, bool, String and List<String>.
  shared_preferences: ^2.0.7

  # 网络请求
  dio: ^4.0.1

  # 时区转换
  timezone: ^0.8.0

  #包检查
  package_info: ^2.0.2

  # 瀑布流
  flutter_staggered_grid_view: ^0.6.1

  #下拉刷新
  pull_to_refresh: ^2.0.0

  #权限控制
  permission_handler: ^8.1.6

  path_provider: ^2.0.2

  app_installer: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Regular                # 字体别名
      fonts:
        - asset: assets/fonts/AlibabaSans-Regular.otf # 字体文件目录
          weight: 700              # 权重 700表示粗体，相当于bold